# Generated by Django 4.0.4 on 2022-05-31 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FashionApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fashionbrands',
            old_name='founded',
            new_name='foundedDate',
        ),
        migrations.RenameField(
            model_name='fashionicons',
            old_name='profesion',
            new_name='profession',
        ),
    ]
