# Generated by Django 4.0.4 on 2022-06-03 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FashionApp', '0003_alter_fashionbrands_foundeddate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmergingDesigners',
        ),
    ]
